#!/usr/bin/env bash

#
# This script will generate a set of training jobs based off the SETTINGS and MODELS arrays.
# Use the SETTINGS to point to one more more files found in the settings directory to determine the models ran.
# The ARGS will then act as the command line arguments to the model module, overwriting the settings files.
# The MODELS array will then be used to determine which models to train on the data generated by the settings files,
#   Any module in the mlpng package can be used, e.g. trainer_lensed or scn_jorik.
#

#this is the sbatch file to use for the jobs
SBATCH_FILE="sbatch/trainer.sbatch"

# The settings files to use for the sims. These should be found in settings/*.json
SETTINGS=(
    # "n32"
    # "n64"
    # "n128"
    "n256"
)

# CLI args to change the command ran, helps prevent needing to change the settings file for small / test changes
# make sure these align with the data generation or you will get errors
# see mlpng/core.py (_parse_args) for more info and available arguments, or to add more
ARGS=(
    "--nsims" "10000"
    "--phi_scale" "1"
    "--shapes" "local"
    "--fnl_range" "-1000" "1000"
)

# The models to train, one job per run. Each name is a module under mlpng/, so
# "trainer_lensed" runs `python -m mlpng.trainer_lensed`. See mlpng/trainer_unlensed.py,
# mlpng/trainer_lensed.py, and mlpng/scn_jorik.py.
MODELS=(
    "trainer_lensed"
    # "trainer_unlensed"
    # "trainer_unlensed_2"
)

# loops through all the SETTINGS files and for each submits a slurm job for each MODEL
for x in "${SETTINGS[@]}"; do
    file="settings/$x.json"
    if [ ! -f "$file" ]; then
        echo "Settings file $file not found, skipping"
        continue
    fi

    echo "Settings $x:"

    for model in "${MODELS[@]}"; do
        JOB_ID=$(sbatch "$SBATCH_FILE" "$model" "$file" "${ARGS[@]}" | awk '{print $4}')
        printf "\tSubmitted %s, with ID %s\n" "$model" "$JOB_ID"
    done
done
