#!/usr/bin/env bash

#
# This script will generate a set of training jobs based off the SETTINGS and MODELS arrays.
# Use the SETTINGS to point to one more more files found in the settings directory to determine the models ran.
# The ARGS will then act as the command line arguments to the model module, overwriting the settings files.
# The MODELS array will then be used to determine which models to train on the data generated by the settings files,
#   Any module in the mlpng package can be used, e.g. optuna_trainer.
#

#this is the sbatch file to use for the jobs
SBATCH_FILE="sbatch/tuner.sbatch"

# The settings files to use for the sims. These should be found in settings/*.json
SETTINGS=(
    # "n32"
    "n64"
    # "n128"
    # "n256"
)

# CLI args to change the command ran, helps prevent needing to change the settings file for small / test changes
# make sure these align with the data generation or you will get errors
# see mlpng/core.py (_parse_args) for more info and available arguments, or to add more
ARGS=(
    "--nsims" "10000"
    "--phi_scale" "1"
    "--shapes" "all"
    "--fnl_range" "-1000" "1000"
    # "--tensorboard"
    # "--wandb"
)

# The model to tune. This is a module under mlpng/, so "optuna_trainer" runs
# `python -m mlpng.optuna_trainer`. See mlpng/optuna_trainer.py.
MODELS=(
    "optuna_trainer"
)

# Number of times to run the tuner (allows for parallel hyperparameter search)
NUM_RUNS=20

# loops through all the SETTINGS files and for each submits a slurm job for each MODEL
for x in "${SETTINGS[@]}"; do
    file="settings/$x.json"
    if [ ! -f "$file" ]; then
        echo "Settings file $file not found, skipping"
        continue
    fi

    echo "Settings $x:"

    for model in "${MODELS[@]}"; do
        for run in $(seq 1 $NUM_RUNS); do
            JOB_ID=$(sbatch "$SBATCH_FILE" "$model" "$file" "${ARGS[@]}" | awk '{print $4}')
            printf "\tSubmitted %s (run %d/%d), with ID %s\n" "$model" "$run" "$NUM_RUNS" "$JOB_ID"
        done
    done
done
